<?php
/**
 * Use the jQuery Browser Rejection library (jReject) to notify customers
 * using old browsers to upgrade
 *
 * @category    Ash
 * @package     Ash_Jreject
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$_helper = Mage::helper('ash_jreject');
?>
<?php if($_helper->isEnabled()): ?>
<script type='text/javascript'>
//<![CDATA[
    <?php
        // turn PHP bool values into JS boolean values
        $enable         = json_encode((bool)$_helper->isEnabled());
        $close          = json_encode((bool)$_helper->getAllowModalClose());
        $closeEsc       = json_encode((bool)$_helper->getAllowModalCloseByEsc());
        $closeCookie    = json_encode((bool)$_helper->getRememberModalCloseWithCookie());

        // turn PHP arrays into JSON-encoded arrays or hashes
        $rejected       = json_encode($_helper->getSelectedBrowserVersions());
        $alternatives   = json_encode($_helper->getBrowserAlternatives());
    ?>

    jQuery.reject({
        display: <?php echo $alternatives; ?>,
        reject: <?php echo $rejected; ?>,
        imagePath: "<?php echo $_helper->getImagePath(); ?>",
        enable: <?php echo $enable; ?>,
        header: "<?php echo $_helper->getCustomHeader(); ?>",
        paragraph1: "<?php echo $_helper->getCustomParagraph1(); ?>",
        paragraph2: "<?php echo $_helper->getCustomParagraph2(); ?>",
        closeMessage: "<?php echo $_helper->getCustomCloseMessage(); ?>",
        closeLink: "<?php echo $_helper->getCustomCloseLink(); ?>",
        closeURL: "<?php echo $_helper->getCustomCloseUrl(); ?>",
        close: <?php echo $close; ?>,
        closeESC: <?php echo $closeEsc; ?>,
        closeCookie: <?php echo $closeCookie; ?>,
        overlayBgColor: "<?php echo $_helper->getOverlayBgColor(); ?>",
        overlayOpacity: <?php echo (float)$_helper->getOverlayOpacity(); ?>,
        fadeInTime: <?php echo (integer)$_helper->getFadeInTime(); ?>,
        fadeOutTime: <?php echo (integer)$_helper->getFadeOutTime(); ?>
    });
//]]>
</script>
<?php endif; ?>
